<?php

/**
 * @file
 * Contains skeletor_page_headers.module.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function skeletor_page_headers_theme() {
  return [
    'skeletor_page_headers__banner_set' => [
       'base hook' => 'paragraph',
    ],
    'skeletor_page_headers__image_banner' => [
       'base hook' => 'paragraph',
    ],
    'skeletor_page_headers__video_banner' => [
       'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function skeletor_page_headers_theme_suggestions_paragraph_alter(array &$suggestions, array $variables) {
  if (in_array('paragraph__skeletor_header_banner_set', $suggestions)) {
    $suggestions[] = 'skeletor_page_headers__banner_set';
  }

  if (in_array('paragraph__skeletor_image_banner', $suggestions)) {
    $suggestions[] = 'skeletor_page_headers__image_banner';
  }

  if (in_array('paragraph__skeletor_video_banner', $suggestions)) {
    $suggestions[] = 'skeletor_page_headers__video_banner';
  }
}

/**
 * Prepares variables for paragraph template.
 *
 * See template_preprocess_paragraph().
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 *   - paragraph: The paragraph object.
 *   - view_mode: View mode; e.g., 'full', 'teaser'...
 */
function template_preprocess_skeletor_page_headers__banner_set(&$variables) {
  _skeletor_page_headers_preprocess_banner($variables);
}

/**
 * Prepares variables for paragraph template.
 *
 * See template_preprocess_paragraph().
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 *   - paragraph: The paragraph object.
 *   - view_mode: View mode; e.g., 'full', 'teaser'...
 */
function template_preprocess_skeletor_page_headers__image_banner(&$variables) {
  _skeletor_page_headers_preprocess_banner($variables);
}


/**
 * Prepares variables for paragraph template.
 *
 * See template_preprocess_paragraph().
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 *   - paragraph: The paragraph object.
 *   - view_mode: View mode; e.g., 'full', 'teaser'...
 */
function template_preprocess_skeletor_page_headers__video_banner(&$variables) {
  _skeletor_page_headers_preprocess_banner($variables);
}

/**
 * Helper function to be called in preprocess paragraph type.
 * Prepares variables for paragraph template.
 *
 * See template_preprocess_paragraph().
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 *   - paragraph: The paragraph object.
 *   - view_mode: View mode; e.g., 'full', 'teaser'...
 */
function _skeletor_page_headers_preprocess_banner(&$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  $variables['paragraph'] = $variables['elements']['#paragraph'];

  // Helpful $content variable for templates.
  $variables += array('content' => array());
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}