
skeletor.site:
  type: config_object
  label: 'Site Information'
  mapping:
    page:
      type: mapping
      label: 'Pages'
      mapping:
        front:
          type: label
          label: 'Default front page'
